package com.example.MyBookShopApp.entity;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.util.Date;


@Entity
@Table(name = "books")
@Getter
@Setter
//@ApiModel(description = "entity representing a book")
public class Book {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    //@ApiModelProperty("id generated by db automatically")
    private Integer id;

    public Book() {
    }
    @Column(columnDefinition = "TEXT")
    private String description;



    //@Column(columnDefinition = "INT")
    private Double discount;

    @Column(columnDefinition = "VARCHAR(255) NOT NULL")
    private String image;

    @Column(columnDefinition = "INT")
    //@ApiModelProperty("bestsellers if eq 1")
    private Integer isBestseller;

   // @Column(columnDefinition = "integer")
    @JsonProperty("price")
    private Integer price;

   // @Column(columnDefinition = "DATE NOT NULL")
    //@ApiModelProperty("date od book publication")
    private Date pubDate;

    @Column(columnDefinition = "VARCHAR(255) NOT NULL")
    //@ApiModelProperty("axaxaxaxa")
    private String slug;

    //@ApiModelProperty("title of book")
    @Column(columnDefinition = "VARCHAR(255) NOT NULL")
    private String title;

    @Override
    public String toString() {
        return "Book{" +
                "id=" + id +
                ", text='" + description + '\'' +
                ", discount=" + discount +
                ", image='" + image + '\'' +
                ", isBestseller=" + isBestseller +
                ", price=" + price +
                ", pubDate=" + pubDate +
                ", slug='" + slug + '\'' +
                ", title='" + title + '\'' +
                '}';
    }
}
