package com.example.MyBookShopApp.entity;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.persistence.*;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.FieldDefaults;

import java.util.Date;


@Entity
@Table(name = "books")
@Getter
@Setter
@FieldDefaults(level = AccessLevel.PRIVATE)
@ToString
@NoArgsConstructor
//@ApiModel(description = "entity representing a book")
public class Book {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    //@ApiModelProperty("id generated by db automatically")
    private Integer id;

    @Column(columnDefinition = "TEXT")
    private String description;

    //@Column(columnDefinition = "INT")
    Double discount;

    @Column(columnDefinition = "VARCHAR(255) NOT NULL")
    String image;

    @Column(columnDefinition = "INT")
    //@ApiModelProperty("bestsellers if eq 1")
    Integer isBestseller;

   // @Column(columnDefinition = "integer")
    @JsonProperty("price")
    Integer price;

   // @Column(columnDefinition = "DATE NOT NULL")
    //@ApiModelProperty("date od book publication")
    Date pubDate;

    @Column(columnDefinition = "VARCHAR(255) NOT NULL")
    //@ApiModelProperty("axaxaxaxa")
    String slug;

    //@ApiModelProperty("title of book")
    @Column(columnDefinition = "VARCHAR(255) NOT NULL")
    private String title;

    @ManyToOne
    @JoinColumn(name = "author_id", referencedColumnName = "id")
    private Authors author;

    private Integer count_of_buyers;

    private Integer count_of_cart;

    private Integer count_of_delay;

    public Long getRoundDiscount(){
     return Math.round(discount);
    }

    public Long getNewPrice(){
        return Math.round(price * (1 - discount/100));
    }

    @Override
    public String toString() {
        return "Book{" +
                "id=" + id +
                ", text='" + description + '\'' +
                ", discount=" + discount +
                ", image='" + image + '\'' +
                ", isBestseller=" + isBestseller +
                ", price=" + price +
                ", pubDate=" + pubDate +
                ", slug='" + slug + '\'' +
                ", title='" + title + '\'' +
                '}';
    }
}
