package com.example.MyBookShopApp.entity;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.persistence.*;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.FieldDefaults;

import java.util.Date;


@Getter
@Setter
@Table(name = "books")
@FieldDefaults(level = AccessLevel.PRIVATE)
@ToString
@NoArgsConstructor
@Entity
//@ApiModel(description = "entity representing a book")
public class Book {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    //@ApiModelProperty("id generated by db automatically")
    Integer id;
    
    @Column(columnDefinition = "TEXT")
    String description;
    
    //@Column(columnDefinition = "INT")
    Double discount;

    @Column(columnDefinition = "VARCHAR(255) NOT NULL")
    String image;

    @Column(columnDefinition = "INT")
    //@ApiModelProperty("bestsellers if eq 1")
    Integer isBestseller;

   // @Column(columnDefinition = "integer")
    @JsonProperty("price")
    Integer price;

   // @Column(columnDefinition = "DATE NOT NULL")
    //@ApiModelProperty("date od book publication")
    Date pubDate;

    @Column(columnDefinition = "VARCHAR(255) NOT NULL")
    //@ApiModelProperty("axaxaxaxa")
    String slug;

    //@ApiModelProperty("title of book")
    @Column(columnDefinition = "VARCHAR(255) NOT NULL")
    String title;
}
