insert into books (author, title, priceOld, price) values ('Drucie Goodbourn', 'exploit real-time e-commerce', '$203.23', '$43.37');
insert into books (author, title, priceOld, price) values ('Marcia Aggiss', 'utilize real-time interfaces', '$260.31', '$35.96');
insert into books (author, title, priceOld, price) values ('Giovanni Bigg', 'extend strategic e-services', '$272.00', '$151.04');
insert into books (author, title, priceOld, price) values ('Duffie Eynon', 'iterate integrated solutions', '$271.58', '$141.40');
insert into books (author, title, priceOld, price) values ('Anselma McKennan', 'cultivate magnetic e-commerce', '$278.43', '$54.44');
insert into books (author, title, priceOld, price) values ('Gert Kira', 'architect vertical ROI', '$282.54', '$102.61');
insert into books (author, title, priceOld, price) values ('Clerc Djakovic', 'disintermediate extensible architectures', '$295.38', '$181.27');
insert into books (author, title, priceOld, price) values ('Stacee Elsy', 'extend leading-edge methodologies', '$283.08', '$97.96');
insert into books (author, title, priceOld, price) values ('Dorotea Bonhill', 'integrate one-to-one systems', '$258.51', '$52.25');
insert into books (author, title, priceOld, price) values ('Minni Bunney', 'revolutionize 24/7 infrastructures', '$260.79', '$33.69');
insert into books (author, title, priceOld, price) values ('Berty Gandley', 'enhance innovative e-services', '$256.54', '$160.98');
insert into books (author, title, priceOld, price) values ('Raynard Tesdale', 'maximize 24/365 e-tailers', '$262.07', '$34.06');
insert into books (author, title, priceOld, price) values ('Joanna Hutfield', 'scale integrated architectures', '$257.66', '$32.97');
insert into books (author, title, priceOld, price) values ('Dannie Glidder', 'e-enable frictionless web services', '$288.19', '$90.52');
insert into books (author, title, priceOld, price) values ('Timmie Adshede', 'strategize B2B channels', '$232.27', '$44.83');
insert into books (author, title, priceOld, price) values ('Fernando Neads', 'syndicate compelling deliverables', '$287.45', '$101.89');
insert into books (author, title, priceOld, price) values ('Teddy Guilliland', 'utilize bleeding-edge users', '$281.37', '$146.21');
insert into books (author, title, priceOld, price) values ('Paloma Grebert', 'cultivate 24/365 networks', '$270.99', '$184.76');
insert into books (author, title, priceOld, price) values ('Kristos Usher', 'embrace plug-and-play platforms', '$278.36', '$77.71');
insert into books (author, title, priceOld, price) values ('Darcey Rohmer', 'target innovative paradigms', '$298.94', '$130.01');
insert into books (author, title, priceOld, price) values ('Cristie Isacsson', 'generate open-source e-business', '$276.57', '$113.25');
insert into books (author, title, priceOld, price) values ('Lindsay Coutthart', 'implement user-centric e-markets', '$254.70', '$115.31');
insert into books (author, title, priceOld, price) values ('Helyn Schneidar', 'utilize magnetic supply-chains', '$279.70', '$77.86');
insert into books (author, title, priceOld, price) values ('Bette-ann Askem', 'e-enable dot-com supply-chains', '$297.83', '$110.15');
insert into books (author, title, priceOld, price) values ('Dom Robuchon', 'facilitate efficient eyeballs', '$232.30', '$131.48');
insert into authors (name, old) values ('Андросенко Александ', 26);
insert into authors (name, old) values ('Анжело Алек', 54);
insert into authors (name, old) values ('Аннандейл Дэви', 74);
insert into authors (name, old) values ('Антонова Натали', 88);
insert into authors (name, old) values ('Анхем Стефа', 22);
insert into authors (name, old) values ('Арден Кэтри', 49);
insert into authors (name, old) values ('Ардова Алис', 17);
insert into authors (name, old) values ('Ариели Дэ', 85);
insert into authors (name, old) values ('Арифуллина Елен', 47);
insert into authors (name, old) values ('Арментроут Дженнифер Л', 20);
insert into authors (name, old) values ('Арментроут Дженнифер Л', 62);
insert into authors (name, old) values ('Арнольд Дэви', 86);
insert into authors (name, old) values ('Арсан Эммануэль', 75);
insert into authors (name, old) values ('Арсеньева Елен', 87);
insert into authors (name, old) values ('Арто Паасилинн', 29);
insert into authors (name, old) values ('Архангельская Мари', 76);
insert into authors (name, old) values ('Арье Вер', 42);
insert into authors (name, old) values ('Астапов Макси', 54);
insert into authors (name, old) values ('Астахов Паве', 39);
insert into authors (name, old) values ('Аствацатуров Андре', 45);
insert into authors (name, old) values ('Атаманов Михаи', 41);
insert into authors (name, old) values ('Афанасьев Александ', 31);
insert into authors (name, old) values ('Ахерн Сесили', 86);
insert into authors (name, old) values ('Байбаков Ива', 86);
insert into authors (name, old) values ('Байер Уилья', 57);
insert into authors (name, old) values ('Бакиров Анва', 32);
insert into authors (name, old) values ('Бакман Фредри', 46);
insert into authors (name, old) values ('Баковец Михаи', 19);
insert into authors (name, old) values ('Баксбаум Джули', 84);
insert into authors (name, old) values ('Бакстер Стиве', 69);
insert into authors (name, old) values ('Бакулина Екатерин', 41);
insert into authors (name, old) values ('Балахнин Алексе', 50);
insert into authors (name, old) values ('Балдаччи Дэви', 75);
insert into authors (name, old) values ('Баллерини Луидж', 20);
insert into authors (name, old) values ('Баневич Арту', 64);
insert into authors (name, old) values ('Банзл Пите', 84);
insert into authors (name, old) values ('Баранова Ирин', 19);
insert into authors (name, old) values ('Барбара Пи', 79);
insert into authors (name, old) values ('Барбери Мюриел', 70);
insert into authors (name, old) values ('Барден Фи', 49);
insert into authors (name, old) values ('Бардуго Ле', 31);
insert into authors (name, old) values ('Баринова Любов', 53);
insert into authors (name, old) values ('Барисо Джасти', 61);
insert into authors (name, old) values ('Вайн Барбар', 59);
insert into authors (name, old) values ('Вайнштейн Стелл', 62);
insert into authors (name, old) values ('Вайцкин Джо', 73);
insert into authors (name, old) values ('Валенте Кэтрин М', 52);
insert into authors (name, old) values ('Валентеева Ольг', 32);
insert into authors (name, old) values ('Валериев Игор', 19);
insert into authors (name, old) values ('Валерия Вербинин', 51);
insert into authors (name, old) values ('Ван Бой Саймо', 59);
insert into authors (name, old) values ('Вапник Эмил', 64);
insert into authors (name, old) values ('Варгас Фре', 42);
insert into authors (name, old) values ('Варго Алексан', 83);
