insert into genre (id, parent_id, name) values (1, 0, 'Лёгкое чтение');
insert into genre (id, parent_id, name) values (2, 1, 'Фантастика');
insert into genre (id, parent_id, name) values (3, 1, 'Боевики');
insert into genre (id, parent_id, name) values (4, 1, 'Детективы');
insert into genre (id, parent_id, name) values (5, 4, 'Триллер');
insert into genre (id, parent_id, name) values (6, 4, 'Крутой детектив');
insert into genre (id, parent_id, name) values (7, 4, 'Иронический детектив');
insert into genre (id, parent_id, name) values (8, 4, 'Про маньяков');
insert into genre (id, parent_id, name) values (9, 4, 'Классический детектив');
insert into genre (id, parent_id, name) values (10, 1, 'Фэнтези');
insert into genre (id, parent_id, name) values (11, 1, 'Романы');
insert into genre (id, parent_id, name) values (12, 1, 'Ужасы');
insert into genre (id, parent_id, name) values (13, 0, 'Серьёзное чтение');
insert into genre (id, parent_id, name) values (14, 13, 'Биографии');
insert into genre (id, parent_id, name) values (15, 0, 'Деловая литература');
insert into genre (id, parent_id, name) values (16, 15, 'Управление экономикой');
insert into genre (id, parent_id, name) values (17, 15, 'Карьера');
insert into genre (id, parent_id, name) values (18, 15, 'Маркетинг, PR, реклама');
insert into genre (id, parent_id, name) values (19, 15, 'Финансы');
insert into genre (id, parent_id, name) values (20, 15, 'Личная эффективность');
insert into genre (id, parent_id, name) values (21, 15, 'Стартапы и создание бизнеса');
insert into genre (id, parent_id, name) values (22, 15, 'Проектный менеджмент');
insert into genre (id, parent_id, name) values (23, 15, 'Корпоративная культура');
insert into genre (id, parent_id, name) values (24, 15, 'Делопроизводство');
insert into genre (id, parent_id, name) values (25, 15  , 'Российская практика');
insert into genre (id, parent_id, name) values (26, 15, 'Управление бизнесом');
insert into genre (id, parent_id, name) values (27, 15, 'Бизнес-процессы');
insert into genre (id, parent_id, name) values (28, 15, 'Лидерство');
insert into genre (id, parent_id, name) values (29, 0, 'Драматургия');
insert into genre (id, parent_id, name) values (30, 29, 'Античная драма');
insert into genre (id, parent_id, name) values (31, 29, 'Комедия');
insert into genre (id, parent_id, name) values (32, 29, 'Сценарий');
insert into genre (id, parent_id, name) values (33, 29, ' Драма, пьеса');
insert into genre (id, parent_id, name) values (34, 29, 'Переписки семиклассниц');
insert into genre (id, parent_id, name) values (35, 1, 'Приключения');
insert into genre (id, parent_id, name) values (36, 0, 'Юмор');
insert into genre (id, parent_id, name) values (37, 36, 'Анекдоты');
insert into genre (id, parent_id, name) values (38, 36, 'Комедийные зарисовки');
insert into genre (id, parent_id, name) values (39, 36, 'Юморески');
insert into genre (id, parent_id, name) values (40, 36, 'Юридическая литература');
