insert into tags (id, name) VALUES (1, 'modern literature');
insert into tags (id, name) VALUES (2, 'classical literature');
insert into tags (id, name) VALUES (3, 'foreign literature');
insert into tags (id, name) VALUES (4, 'fantasy');
insert into tags (id, name) VALUES (5, 'English literature');
insert into tags (id, name) VALUES (6, 'Russian literature');
insert into tags (id, name) VALUES (7, 'American literature');
insert into tags (id, name) VALUES (8, 'fiction');
insert into tags (id, name) VALUES (9, 'children''s literature');
insert into tags (id, name) VALUES (10, 'detective');
insert into tags (id, name) VALUES (11, 'love');
insert into tags (id, name) VALUES (12, 'mysticism');
insert into tags (id, name) VALUES (13, 'humor');
insert into tags (id, name) VALUES (14, 'adventures');
insert into tags (id, name) VALUES (15, 'fairy tale');
insert into tags (id, name) VALUES (16, 'french literature');
insert into tags (id, name) VALUES (17, 'england');
insert into tags (id, name) VALUES (18, 'fiction');
insert into tags (id, name) VALUES (19, 'psychology philosophy');
insert into tags (id, name) VALUES (20, 'filmed');
insert into tags (id, name) VALUES (21, 'typo kaif');